apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespacelabel-webhook-deployment
  namespace: namespacelabel-assignment-system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image: taldebi/tal:v1.14
          command:
            - /manager
          args:
            - --leader-elect
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          env:
            - name: ENABLE_WEBHOOKS
              value: "true"
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-server-cert

