apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-namespacelabel
  labels:
    app: my-webhook
webhooks:
  - name: validate-namespacelabel.dana.io
    rules:
      - apiGroups: ["dana.dana.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["namespacelabels"]
    clientConfig:
      service:
        name: webhook-service
        namespace: namespacelabel-assignment-system
        path: "/validate-namespacelabel"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lVQXg4Q2xNME4w
        QUlUczF0czZoWEZpL0llcnlVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1dk
        MlZpYUc5dmF5MXpaWEoyYVdObExtNXpMbk4yWXpBZUZ3MHlOREEyTWpjeQpNak00TXpGYUZ3MHlO
        VEEyTWpjeU1qTTRNekZhTUNFeEh6QWRCZ05WQkFNTUZuZGxZbWh2YjJzdGMyVnlkbWxqClpTNXVj
        eTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNWYmdseHRI
        UEgKZWVSbU1OOGY3MER1ci9GMEJsb0R2ZzZCODE0SmZ5WG5YQ3g3SEtVMnRPMUtpd1FobVV3L040
        NXZJWHZudFo2NgptUWwyUEc1S2dBUmJzcmlvaVRXV3ZCNzE2RTFCY1NjcjZkZVE3dVpyRzlIL25O
        NGlpSWJiK1g4V1Fqeld2T2dtCmt3Q1A1MlhiQUdhUVV1OTRqdktYdURDMFpHTHNHSnhzK2Eyd1V3
        TXFRQnBBaW51d3NuVWswSitGSi9kNndnZzgKYk5VNnBvdklOSi84QmZHMW9VTStLb3BHVFRVbWFn
        elY5L2Z0RnVwNndlcnVpNG9ZT1ZZWWFvR0J5V3hENGdFawpTaWZhcXlCRE8ycVM1VXNhaXpiazBM
        Z1c1OHlrOWZHbVYxdXA3RTF4RU5UWURBS2wvNUV3ZGtUN01iaEE4K2JhClhrRkp6UEZ5aVJEM0Fn
        TUJBQUdqZkRCNk1Ga0dBMVVkRVFSU01GQ0NUbTVoYldWemNHRmpaV3hoWW1Wc0xXRnoKYzJsbmJt
        MWxiblF0ZDJWaWFHOXZheTF6WlhKMmFXTmxMbTVoYldWemNHRmpaV3hoWW1Wc0xXRnpjMmxuYm0x
        bApiblF0YzNsemRHVnRMbk4yWXpBZEJnTlZIUTRFRmdRVXdWTHJZMzJnbjRHb2dqOEU4Y1hXQi9p
        WDJvUXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUlidVBDOUNvMWJnMzJWZTB6blBrQkMwSndE
        NkZXblpXWVc3eW9zTlp0aWUKNGt3ZytMMjNNUFcvSVRteHdZSlJwZDE0VmlFK1d3Y0dYMFFSOFNa
        ajBzNTlkbFZiQ3I0Tlk2dkw0NG9Fd01KeApCODVMcDNtZ1J4OWU2WXhkVGhzcnlHMCtOd2NIbnlS
        UzFPK0p0ME41b3JDb3dma0V0K1N1Vy8rR2l1dXhoK1V6ClVYMVV1alUrRTRsUENka3ozQ2huS1VF
        ZWJtOWx0WHZURGw2RFBLSnhBbHlvZ3NBQ2tSQUFVYWd3SDFUWng2dGUKYzBzTzJWbmt2L0FERVBV
        M0xwYW1JRGl2ZVZGSGtlODlld2h3TG8ybGg1MDJlZFpqL0lnZDV6STBIWVZlSjZDcgpCeWllNmta
        UEdQaVV0b2tkcS9GRmYvUk5HSk1tUkhmMjhkNUtFZEs3V3dZPQotLS0tLUVORCBDRVJUSUZJQ0FU
        RS0tLS0tCg==
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
