apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: cert-manager
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: cert-manager
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image: taldebi/tal:v1.19
          command:
            - /manager
          args:
            - --leader-elect
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          env:
            - name: ENABLE_WEBHOOKS
              value: "true"
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-server-cert
