# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacelabels.dana.dana.io
  namespace: cert-manager
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: cert-manager
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
